"""Harness registry, detection and per-harness configuration writers.

Each :class:`Harness` knows how to (best-effort) *detect* whether it is present and
how to *configure* it so it talks to the Skore Hub agent's OpenAI-compatible
endpoint. The writers deliberately differ because harnesses are configured very
differently (project file vs. global file vs. env vars vs. a translation proxy).

Credentials stay user-managed: the API key is never written to a file, only
*referenced* (``{env:...}`` for opencode, ``$SKORE_HUB_API_KEY`` in env files,
``${{ env.SKORE_HUB_API_KEY }}`` for Continue). Interactive device-flow tokens are
refreshed on the fly and emitted as a bearer.
"""

from __future__ import annotations

import json
import os
import shutil
from collections.abc import Callable
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from skore_cli._skore import auth as _auth
from skore_cli._style import console

API_KEY_ENV = "SKORE_HUB_API_KEY"
DEFAULT_HUB_URL = "http://127.0.0.1:8000"
DEFAULT_MODEL_ID = "skore-agent"

# Marker recording what `skore agent init` configured, so `status` is trivial.
MARKER_FILENAME = ".skore-agent.json"

# Visible connection file written by the generic harness (paste-friendly).
GENERIC_CONFIG_FILENAME = "skore-agent.json"

# Header naming the hub workspace the agent is attached to (a workspace public id).
WORKSPACE_HEADER = "X-Skore-Workspace"

# opencode provider name: no dots (avoids the opencode option-dropping bug #5674).
OPENCODE_PROVIDER_KEY = "skore"
OPENCODE_SCHEMA = "https://opencode.ai/config.json"
SESSION_HEADER = "X-Skore-Session-Id"
SESSION_PLUGIN_FILENAME = "skore-session.js"
SESSION_PLUGIN_SOURCE = f"""\
// Auto-generated by `skore agent init`. Forwards opencode's session id to the
// Skore Hub agent so the hub can resume the matching conversation history.
export const SkoreSession = async () => ({{
  "chat.headers": async (input, output) => {{
    const id = input?.provider?.info?.id ?? input?.provider?.id;
    if (id === "{OPENCODE_PROVIDER_KEY}" && input?.sessionID) {{
      output.headers["{SESSION_HEADER}"] = input.sessionID;
    }}
  }},
}});
"""


def base_url(hub_url: str) -> str:
    """Return the OpenAI-compatible base URL the harness should point at."""
    return f"{hub_url.rstrip('/')}/v1"


@dataclass(frozen=True)
class Credential:
    """A resolved hub credential.

    ``kind`` is ``"api_key"`` (user-managed via ``SKORE_HUB_API_KEY``, never
    embedded), ``"bearer"`` (an interactive device-flow access token, embedded as
    a literal) or ``"none"``.
    """

    kind: str
    token: str = ""


def resolve_credential() -> Credential:
    """Resolve the hub credential, mirroring the Python authentication.

    Prefers the user-managed API key (referenced, never stored); otherwise
    refreshes the persisted interactive token (relaunching the device login if the
    refresh token is dead) and returns it as a bearer.
    """
    if os.environ.get(API_KEY_ENV):
        return Credential("api_key")

    token = _auth("token").fresh_token(relogin=True)
    if token and token.get("access_token"):
        return Credential("bearer", token["access_token"])
    return Credential("none")


def header_pair(cred: Credential) -> tuple[str, str] | None:
    """Return the ``(name, value)`` auth header, opencode/generic ``{env:}`` style."""
    if cred.kind == "api_key":
        return ("X-API-Key", f"{{env:{API_KEY_ENV}}}")
    if cred.kind == "bearer":
        return ("Authorization", f"Bearer {cred.token}")
    return None


def workspace_headers(ctx: ConfigureContext) -> dict[str, str]:
    """Return the workspace-attachment header, if a workspace slug is set.

    API-key credentials are already bound to a workspace server-side, so the
    header is only meaningful (and only written) for the interactive bearer path.
    """
    if ctx.hub_workspace:
        return {WORKSPACE_HEADER: ctx.hub_workspace}
    return {}


def fetch_workspaces(hub_url: str, cred: Credential) -> list[tuple[str, str]]:
    """List the workspaces the user can attach to, as ``(public_id, name)`` pairs.

    Calls the hub ``GET /identity/workspaces`` with the resolved credential. Used
    only by the interactive bearer picker; API-key auth needs no selection.
    """
    import httpx

    if cred.kind == "api_key":
        token = os.environ.get(API_KEY_ENV, "")
        headers = {"X-API-Key": token}
    elif cred.kind == "bearer":
        headers = {"Authorization": f"Bearer {cred.token}"}
    else:
        headers = {}

    url = f"{hub_url.rstrip('/')}/identity/workspaces"
    response = httpx.get(url, headers=headers, timeout=30, follow_redirects=True)
    response.raise_for_status()
    payload = response.json()
    items = payload.get("items", payload) if isinstance(payload, dict) else payload

    workspaces: list[tuple[str, str]] = []
    for item in items or []:
        public_id = item.get("public_id") or item.get("slug")
        if not public_id:
            continue
        workspaces.append((public_id, item.get("name") or public_id))
    return workspaces


@dataclass
class ConfigureContext:
    """Inputs shared by every harness writer."""

    workspace: Path
    hub_url: str
    model_id: str
    cred: Credential
    # Hub workspace slug (public id) the agent is attached to; only written for
    # the bearer path (API keys are already workspace-bound server-side).
    hub_workspace: str | None = None
    # opencode-only:
    write_session_plugin: bool = True
    # generic-only:
    write_file: bool = True

    @property
    def base_url(self) -> str:
        return base_url(self.hub_url)


def _no_credential_note() -> None:
    console.print(
        f"  [skore.muted](no credential resolved -- set {API_KEY_ENV} or run "
        "`skore hub login`, then re-run init)[/]"
    )


def _warn_workspace_header_unsupported(ctx: ConfigureContext) -> None:
    """Warn when a bearer setup cannot carry the workspace header.

    This harness cannot send custom headers, so an interactive-login (bearer)
    token cannot be scoped to a workspace and the hub now rejects unscoped agent
    calls. A workspace-scoped API key carries the binding intrinsically.
    """
    if ctx.cred.kind == "bearer":
        console.print(
            f"[yellow]  This harness cannot send the {WORKSPACE_HEADER} header, so "
            "an interactive-login token cannot be scoped to a workspace and the "
            f"hub will reject the call. Use a workspace-scoped API key "
            f"({API_KEY_ENV}) instead.[/]"
        )


# --------------------------------------------------------------------------- #
# Writers
# --------------------------------------------------------------------------- #
def _configure_opencode(ctx: ConfigureContext) -> dict[str, Any]:
    """Write/merge ``opencode.json`` + the session-binding plugin."""
    config_path = ctx.workspace / "opencode.json"
    config: dict = {}
    if config_path.exists():
        try:
            config = json.loads(config_path.read_text() or "{}")
        except json.JSONDecodeError:
            console.print(
                "[yellow]  existing opencode.json is invalid JSON; backing it up.[/]"
            )
            config_path.rename(config_path.with_suffix(".json.bak"))
            config = {}

    options: dict = {"baseURL": ctx.base_url}
    headers: dict[str, str] = {}
    pair = header_pair(ctx.cred)
    if pair:
        headers[pair[0]] = pair[1]
    headers.update(workspace_headers(ctx))
    if headers:
        options["headers"] = headers

    config.setdefault("$schema", OPENCODE_SCHEMA)
    config.setdefault("provider", {})
    config["provider"][OPENCODE_PROVIDER_KEY] = {
        "npm": "@ai-sdk/openai-compatible",
        "name": "Skore Hub Agent",
        "options": options,
        "models": {ctx.model_id: {"name": "Skore Agent"}},
    }
    config_path.write_text(json.dumps(config, indent=2) + "\n")
    console.print(f"[skore.ok]+[/] wrote [skore.path]{config_path}[/]")

    session_plugin = False
    if ctx.write_session_plugin:
        plugin_path = ctx.workspace / ".opencode" / "plugin" / SESSION_PLUGIN_FILENAME
        plugin_path.parent.mkdir(parents=True, exist_ok=True)
        plugin_path.write_text(SESSION_PLUGIN_SOURCE)
        session_plugin = True
        console.print(
            f"[skore.ok]+[/] wrote [skore.path]{plugin_path}[/] "
            "[skore.muted](binds the hub session to the opencode conversation)[/]"
        )

    console.print(
        "\nNext steps:\n"
        f"  1. Run [skore.skill]opencode[/] in [skore.path]{ctx.workspace}[/]\n"
        f"  2. Pick the '[skore.skill]{ctx.model_id}[/]' model and start iterating."
    )
    if ctx.cred.kind == "api_key":
        console.print(
            f"  [skore.muted](export {API_KEY_ENV} in opencode's shell so the "
            "{env:...} reference resolves)[/]"
        )
    return {"config_path": str(config_path), "session_plugin": session_plugin}


def _configure_copilot(ctx: ConfigureContext) -> dict[str, Any]:
    """Write a sourceable env file for the GitHub Copilot CLI (BYOK)."""
    env_path = ctx.workspace / "skore-agent.env"
    if ctx.cred.kind == "bearer":
        api_key_line = f'export COPILOT_PROVIDER_API_KEY="{ctx.cred.token}"'
    else:
        api_key_line = f'export COPILOT_PROVIDER_API_KEY="${API_KEY_ENV}"'
    lines = [
        "# Source this before running `copilot`:  source skore-agent.env",
        f'export COPILOT_PROVIDER_BASE_URL="{ctx.base_url}"',
        'export COPILOT_PROVIDER_TYPE="openai"',
        f'export COPILOT_MODEL="{ctx.model_id}"',
        api_key_line,
        "",
    ]
    env_path.write_text("\n".join(lines))
    console.print(f"[skore.ok]+[/] wrote [skore.path]{env_path}[/]")
    _warn_workspace_header_unsupported(ctx)
    console.print(
        "\nNext steps:\n"
        f"  1. [skore.skill]source {env_path.name}[/] "
        f"in [skore.path]{ctx.workspace}[/]"
    )
    if ctx.cred.kind == "api_key":
        console.print(f"     [skore.muted](with {API_KEY_ENV} exported)[/]")
    console.print("  2. Run [skore.skill]copilot[/] and start iterating.")
    return {"env_file": str(env_path)}


def _configure_continue(ctx: ConfigureContext) -> dict[str, Any]:
    """Merge a model block into the global ``~/.continue/config.yaml``."""
    try:
        import yaml
    except ImportError as error:  # pragma: no cover - exercised via the CLI
        raise _yaml_missing() from error

    config_dir = Path.home() / ".continue"
    config_dir.mkdir(parents=True, exist_ok=True)
    config_path = config_dir / "config.yaml"

    config: dict = {}
    if config_path.exists():
        try:
            config = yaml.safe_load(config_path.read_text()) or {}
        except yaml.YAMLError:
            console.print(
                "[yellow]  existing config.yaml is invalid YAML; backing it up.[/]"
            )
            config_path.rename(config_path.with_suffix(".yaml.bak"))
            config = {}
        else:
            backup = config_path.with_suffix(".yaml.bak")
            backup.write_text(config_path.read_text())
            console.print(f"[skore.muted]  backed up existing config to {backup}[/]")

    config.setdefault("name", "My Config")
    config.setdefault("version", "0.0.1")
    config.setdefault("schema", "v1")

    pair = header_pair(ctx.cred)
    if ctx.cred.kind == "api_key":
        headers = {"X-API-Key": f"${{{{ env.{API_KEY_ENV} }}}}"}
    elif pair:
        headers = {pair[0]: pair[1]}
    else:
        headers = {}
    headers.update(workspace_headers(ctx))

    model_block = {
        "name": "Skore Hub Agent",
        "provider": "openai",
        "model": ctx.model_id,
        "apiBase": ctx.base_url,
        "roles": ["chat", "edit", "apply"],
        "capabilities": ["tool_use"],
    }
    if headers:
        model_block["requestOptions"] = {"headers": headers}

    models = [m for m in config.get("models", []) if m.get("name") != "Skore Hub Agent"]
    models.append(model_block)
    config["models"] = models

    config_path.write_text(yaml.safe_dump(config, sort_keys=False))
    console.print(f"[skore.ok]+[/] updated [skore.path]{config_path}[/]")
    console.print(
        "\nNext steps:\n"
        "  1. Reload the Continue extension in your IDE.\n"
        "  2. Pick the '[skore.skill]Skore Hub Agent[/]' model in Continue."
    )
    if ctx.cred.kind == "api_key":
        console.print(
            f"  [skore.muted](Continue resolves ${{{{ env.{API_KEY_ENV} }}}}; "
            f"export {API_KEY_ENV} in the IDE's environment)[/]"
        )
    return {"config_path": str(config_path), "scope": "global"}


def _configure_cline(ctx: ConfigureContext) -> dict[str, Any]:
    """Best-effort: write the workspace ``.vscode/settings.json`` provider keys.

    Cline stores the API key in VS Code's secret storage (not settings.json) and
    its setting keys vary by version, so we write the provider/base-URL/model and
    ask the user to paste the key in the Cline panel.
    """
    settings_path = ctx.workspace / ".vscode" / "settings.json"
    settings_path.parent.mkdir(parents=True, exist_ok=True)

    settings: dict = {}
    if settings_path.exists():
        try:
            settings = json.loads(settings_path.read_text() or "{}")
        except json.JSONDecodeError:
            console.print(
                "[yellow]  existing settings.json is invalid JSON; backing it up.[/]"
            )
            settings_path.rename(settings_path.with_suffix(".json.bak"))
            settings = {}

    settings["cline.apiProvider"] = "openai-compatible"
    settings["cline.openAiBaseUrl"] = ctx.base_url
    settings["cline.apiModelId"] = ctx.model_id
    settings_path.write_text(json.dumps(settings, indent=2) + "\n")
    console.print(f"[skore.ok]+[/] wrote [skore.path]{settings_path}[/]")
    _warn_workspace_header_unsupported(ctx)
    console.print(
        "\nNext steps:\n"
        "  1. Open the Cline panel in VS Code (gear icon) and confirm provider "
        "[skore.skill]OpenAI Compatible[/], base URL and model.\n"
        "  2. Paste your hub API key in the [bold]API Key[/] field "
        "[skore.muted](Cline stores secrets in VS Code, not settings.json).[/]\n"
        "[skore.muted]  Setting keys vary by Cline version; if base URL/model did "
        "not pre-fill, set them in the panel.[/]"
    )
    return {"settings_path": str(settings_path), "scope": "vscode"}


def _configure_claude_code(ctx: ConfigureContext) -> dict[str, Any]:
    """Experimental: generate a LiteLLM proxy config + env for Claude Code.

    Claude Code speaks the Anthropic wire format, so it needs a proxy translating
    Anthropic <-> our OpenAI ``/v1``. We generate the LiteLLM config and the env
    pointing Claude Code at it; the user runs the proxy.
    """
    try:
        import yaml
    except ImportError as error:  # pragma: no cover - exercised via the CLI
        raise _yaml_missing() from error

    proxy_path = ctx.workspace / "litellm.skore.yaml"
    env_path = ctx.workspace / "skore-agent.env"

    pair = header_pair(ctx.cred)
    if ctx.cred.kind == "api_key":
        headers = {"X-API-Key": f"os.environ/{API_KEY_ENV}"}
    elif pair:
        headers = {pair[0]: pair[1]}
    else:
        headers = {}
    headers.update(workspace_headers(ctx))

    litellm_params: dict = {
        "model": f"openai/{ctx.model_id}",
        "api_base": ctx.base_url,
        "api_key": "skore-unused",
    }
    if headers:
        litellm_params["headers"] = headers

    proxy_config = {
        "model_list": [{"model_name": ctx.model_id, "litellm_params": litellm_params}]
    }
    proxy_path.write_text(yaml.safe_dump(proxy_config, sort_keys=False))
    env_path.write_text(
        "# Source this before running `claude`:  source skore-agent.env\n"
        'export ANTHROPIC_BASE_URL="http://127.0.0.1:4000"\n'
        'export ANTHROPIC_AUTH_TOKEN="skore-litellm"\n'
    )
    console.print(f"[skore.ok]+[/] wrote [skore.path]{proxy_path}[/]")
    console.print(f"[skore.ok]+[/] wrote [skore.path]{env_path}[/]")
    console.print(
        "\n[yellow]Claude Code support is experimental[/] (needs an "
        "Anthropic<->OpenAI proxy).\n"
        "Next steps:\n"
        "  1. [skore.skill]pip install 'litellm\\[proxy]'[/]\n"
        f"  2. [skore.skill]litellm --config {proxy_path.name}[/] "
        "[skore.muted](serves on :4000)[/]\n"
        f"  3. [skore.skill]source {env_path.name}[/]"
    )
    if ctx.cred.kind == "api_key":
        console.print(f"     [skore.muted](with {API_KEY_ENV} exported)[/]")
    console.print("  4. Run [skore.skill]claude[/] and pick the model.")
    return {"proxy_config": str(proxy_path), "env_file": str(env_path)}


def _configure_generic(ctx: ConfigureContext) -> dict[str, Any]:
    """Print (and optionally write) connection values for any OpenAI client."""
    console.print(
        "\nConnection values for any OpenAI-compatible harness:\n"
        f"  base URL : [skore.path]{ctx.base_url}[/]\n"
        f"  model id : [skore.skill]{ctx.model_id}[/]"
    )
    pair = header_pair(ctx.cred)
    headers: dict[str, str] = {}
    if pair:
        headers[pair[0]] = pair[1]
    headers.update(workspace_headers(ctx))
    if pair:
        console.print(f"  header   : {pair[0]}: {pair[1]}")
    else:
        _no_credential_note()
    for name, value in workspace_headers(ctx).items():
        console.print(f"  header   : {name}: {value}")

    extra: dict[str, Any] = {}
    if ctx.write_file:
        out_path = ctx.workspace / GENERIC_CONFIG_FILENAME
        payload = {
            "baseURL": ctx.base_url,
            "model": ctx.model_id,
            "headers": headers,
        }
        out_path.write_text(json.dumps(payload, indent=2) + "\n")
        console.print(f"\n[skore.ok]+[/] wrote [skore.path]{out_path}[/]")
        extra["config_file"] = str(out_path)

    console.print(
        "\n[skore.muted]Paste these into your harness's OpenAI-compatible provider "
        "settings. The hub loads probabl-skills server-side (IP isolation).[/]"
    )
    return extra


def _yaml_missing():
    import rich_click as click

    return click.ClickException(
        "this harness needs PyYAML (install it with `pip install "
        "'skore-cli[agent]'` or `pip install pyyaml`)."
    )


# --------------------------------------------------------------------------- #
# Detection
# --------------------------------------------------------------------------- #
def _detect_opencode(workspace: Path) -> bool:
    if (workspace / "opencode.json").exists():
        return True
    return shutil.which("opencode") is not None


def _detect_copilot(workspace: Path) -> bool:
    return shutil.which("copilot") is not None


def _detect_continue(workspace: Path) -> bool:
    return (Path.home() / ".continue").exists()


def _detect_cline(workspace: Path) -> bool:
    if (workspace / ".vscode").exists():
        return True
    ext_dir = Path.home() / ".vscode" / "extensions"
    return ext_dir.is_dir() and any(ext_dir.glob("saoudrizwan.claude-dev*"))


def _detect_claude_code(workspace: Path) -> bool:
    return (Path.home() / ".claude").exists() or shutil.which("claude") is not None


def _detect_never(workspace: Path) -> bool:
    return False


# --------------------------------------------------------------------------- #
# Registry
# --------------------------------------------------------------------------- #
@dataclass(frozen=True)
class Harness:
    """A configurable agent harness."""

    name: str
    label: str
    detect: Callable[[Path], bool]
    configure: Callable[[ConfigureContext], dict[str, Any]]
    session_binding: str = "fallback"  # "plugin" | "fallback"
    extras: tuple[str, ...] = field(default=())


HARNESSES: dict[str, Harness] = {
    "opencode": Harness(
        "opencode",
        "opencode  -  project config + session binding (turnkey)",
        _detect_opencode,
        _configure_opencode,
        session_binding="plugin",
    ),
    "copilot": Harness(
        "copilot",
        "GitHub Copilot CLI  -  sourceable env file",
        _detect_copilot,
        _configure_copilot,
    ),
    "continue": Harness(
        "continue",
        "Continue  -  global ~/.continue/config.yaml",
        _detect_continue,
        _configure_continue,
    ),
    "cline": Harness(
        "cline",
        "Cline  -  VS Code settings (best-effort; paste key in panel)",
        _detect_cline,
        _configure_cline,
    ),
    "claude-code": Harness(
        "claude-code",
        "Claude Code  -  LiteLLM proxy config (experimental)",
        _detect_claude_code,
        _configure_claude_code,
    ),
    "generic": Harness(
        "generic",
        "generic  -  print values for any OpenAI-compatible client",
        _detect_never,
        _configure_generic,
    ),
}

HARNESS_NAMES = list(HARNESSES)


def detect_harnesses(workspace: Path) -> list[str]:
    """Return the names of harnesses that look present, in registry order."""
    return [
        name
        for name, harness in HARNESSES.items()
        if name != "generic" and harness.detect(workspace)
    ]
